"""help_me_again

Revision ID: 20250123_help_me_again
Revises: 20250123_help_me
Create Date: 2025-01-23 15:10:56.712952+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250123_help_me_again'
down_revision = '20250123_help_me'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
