"""help_me

Revision ID: 20250123_help_me
Revises: 20250107_added_tanecnici
Create Date: 2025-01-23 15:02:02.639580+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250123_help_me'
down_revision = '20250107_added_tanecnici'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bydliste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pocet_deti')
    op.drop_table('tanecnici')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanecnici',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jmeno', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lat', sa.INTEGER(), nullable=False),
    sa.Column('stt', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pocet_deti',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jmeno', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pocet_deti', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bydliste')
    # ### end Alembic commands ###
